# Generated by Django 4.1.3 on 2023-01-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('datatime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
