# Generated by Django 4.1.3 on 2023-01-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='audios/')),
                ('datatime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
