# Generated by Django 4.1.3 on 2023-01-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('respponsedata', models.JSONField()),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('service', models.CharField(max_length=100)),
                ('serivceId', models.CharField(max_length=100)),
                ('serivceLocation', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('datatime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
