# Generated by Django 4.1.3 on 2023-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_response_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('files', models.FileField(upload_to='files/')),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('filetype', models.CharField(max_length=100)),
            ],
        ),
    ]
