# Generated by Django 4.1.3 on 2023-01-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audioName',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='fileName',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='imageName',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
