# Generated by Django 4.1.3 on 2023-01-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_audio_audioname_files_filename_image_imagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='serivceId',
        ),
        migrations.AddField(
            model_name='response',
            name='serivcepaths',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
