# Generated by Django 4.1.3 on 2023-01-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_response_serivceid_response_serivcepaths'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='serivceLocation',
            new_name='serviceLocation',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='serivcepaths',
            new_name='servicepaths',
        ),
    ]
